name: Testing => Run full test suite
on:
  push:
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: yarn
    - name: Unit tests => with Jest
      run: yarn testu
    - name: Component tests => with Jest
      run: yarn testc
    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps chromium
    - name: E2E test  => with Playwright
      run: yarn teste
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
